# Copyright (c) 2012-2018 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
---
kind: Template
apiVersion: v1
metadata:
  name: openshift-identity-provider-certificate
  annotations:
    description: Che
objects:
- apiVersion: v1
  stringData:
    ca.crt: >-
      ${CERTIFICATE}
  kind: Secret
  metadata:
    name: openshift-identity-provider
    namespace: che
  type: Opaque
parameters:
- name: CERTIFICATE
  displayName: Openshift console certificate
labels:
  app: keycloak
  template: openshift-identity-provider-certificate
